### ISSUE TITLE
ionic2  Unexpected value 'MultiPickerModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by lijieray** [raychenfj/ion-multi-picker#35]
d:\yk>ionic build android

> ionic-app-scripts build

[23:05:13]  ionic-app-scripts 0.0.45
[23:05:13]  build prod started ...
[23:05:13]  clean started ...
[23:05:13]  clean finished in 4 ms
[23:05:13]  copy started ...
[23:05:13]  ngc started ...
[23:05:13]  copy finished in 90 ms
[23:05:18]  Error: Unexpected value 'MultiPickerModule' imported by the module '
AppModule'
[23:05:18]  ngc failed
[23:05:18]  ionic-app-script task: "build"
[23:05:18]  Error: Error

npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:build" "--"
npm ERR! node v6.9.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts
build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world pac
kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

d:\yk>ionic -version 
2.1.18

**Comment by raychenfj** [comment]
Hi @lijieray,
I believe this issue is solved in #32 .
I notice your `@ionic/app-scripts` is not up-to-date, so can you try to update it to `0.0.47` ?
And can you start your app in browser by running `ionic serve` ?

**Comment by lijieray** [comment]
@raychenfj 
I try @ionic/app-script updateto 0.0.47,but problem remains.
ionic serve,start  app in browser can run.
